version: '3.1'
services:
  web:
    image: prodemge/procrm:1.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - procrm-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
   db:
    image: postgres:15
    environment:
      - POSTGRES_DB=procrmdb
      - POSTGRES_PASSWORD=procrm
      - POSTGRES_USER=procrm
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - procrm-db-data:/var/lib/postgresql/data/pgdata
volumes:
  procrm-data:
  procrm-db-data:

